### ISSUE TITLE
Unable to open issue with spacehaven-mod-loader

### ISSUE THREAD

**Issue by cbacott** [CyanBlob/CyanBlob#1]
Hello,

Apologies for going this route, I just couldn't find a way otherwise to contact. I am having a failure to launch the game under Linux with your fork of this modloader, which happens to be the the only fork that appears to function under linux. The error says to open an issue with your repo fork, and attach the log, however when I go to your project Issues don't appear to be enabled on it, so I cannot. It seems that functionality has to be enabled on your end.

**Comment by CyanBlob** [comment]
Hi cbacott,

I didn't realize that I had issues disabled. Thanks for the heads up! Could you please give me more information about the issue you're having? Which mods are you trying to launch with?

**Comment by cbacott** [comment]
Thanks for the reply! 

I'll just paste the logs.txt here, it's pretty short. It looks like a python tk/tcl error, honestly:

```
Space Haven Modloader v0.11.5
Logging to /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods
Discovered game at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/spacehaven
  gamePath: /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/spacehaven
  modPath: /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods
  jarPath: /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/spacehaven.jar
  No active mods
Loading game information...
  Version: 0.17.5
Locating mods...
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/PaperFox Adv Assembler build basic...
    Minimum Loader Version: 0.10.0
    Finished loading Advanced Assembler Can Build Basic Blocks
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/PaperFox In-Hull Storage...
    Minimum Loader Version: 0.10.0
    Finished loading PaperFox In-Hull Storage
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/PaperFox In-floor Power Node...
    Minimum Loader Version: 0.10.0
    Finished loading In-floor Power Node
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/Smaller Toilet...
    Minimum Loader Version: 0.10.0
    Finished loading Smaller Toilet
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/Wall Mount Life Support 1.1...
    Minimum Loader Version: 0.10.0
    Finished loading Wall Mount Life Support
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/Vertical Agriculture 1.1...
    Minimum Loader Version: 0.10.0
    Finished loading Vertical Agriculture
  Loading mod at /home/ctrlrisc/.local/share/Steam/steamapps/common/SpaceHaven/mods/In-Hull Bunks...
    Minimum Loader Version: 0.10.0
    Finished loading In-Hull Bunks
!! Exception !!
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/storage/home-current/Archive/GameMods/SpaceHaven/spacehaven-modloader-0.11.5/./spacehaven-modloader.py", line 635, in launch_wrapper
    self.start_background_task(task, message)
  File "/storage/home-current/Archive/GameMods/SpaceHaven/spacehaven-modloader-0.11.5/./spacehaven-modloader.py", line 534, in start_background_task
    self.disable_UI(message)
  File "/storage/home-current/Archive/GameMods/SpaceHaven/spacehaven-modloader-0.11.5/./spacehaven-modloader.py", line 521, in disable_UI
    self.config(cursor = 'wait')
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1702, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1692, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad cursor spec "wait"

```

It didn't really seem like it was any mod in particular based on the error message. I'd try debugging it myself, but I am not as strong in Python as I am in other languages.

**Comment by CyanBlob** [comment]
That seems to be coming from here: https://github.com/CyanBlob/spacehaven-modloader/blob/master/spacehaven-modloader.py#L521C15-L521C15 

I'm not sure why this would be failing for you (I'm not very familiar with Python either; I started working on this mod loader because it was abandoned), but can you try commenting this line out? It seems to just be updating the cursor which shouldn't matter anyways

**Comment by cbacott** [comment]
Looks like that sorted it out. It looks like the original author was making sure good UX was being followed and was trying to set the cursor to the busy to provide feedback while beginning the merge process, but that state must no longer be valid. 

It seems some of the mods I had been trying are busted, which is to be expected, but I was able to launch once I disabled those. Thanks a bunch, I should have tried that myself but was too lazy to try debugging it.
